# Form implementation generated from reading ui file 'c:\Users\HEXAOV\Desktop\l2_gui\Update_V2\ActMsgbox.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ActMsgbox(object):
    def setupUi(self, ActMsgbox):
        ActMsgbox.setObjectName("ActMsgbox")
        ActMsgbox.resize(364, 145)
        self.pushButton = QtWidgets.QPushButton(parent=ActMsgbox)
        self.pushButton.setGeometry(QtCore.QRect(270, 110, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(parent=ActMsgbox)
        self.label.setGeometry(QtCore.QRect(20, 10, 331, 61))
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(parent=ActMsgbox)
        self.textBrowser.setGeometry(QtCore.QRect(20, 70, 331, 25))
        self.textBrowser.setMouseTracking(True)
        self.textBrowser.setAcceptDrops(True)
        self.textBrowser.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhMultiLine)
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.WidgetWidth)
        self.textBrowser.setAcceptRichText(True)
        self.textBrowser.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextBrowserInteraction)
        self.textBrowser.setOpenLinks(True)
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(ActMsgbox)
        QtCore.QMetaObject.connectSlotsByName(ActMsgbox)

    def retranslateUi(self, ActMsgbox):
        _translate = QtCore.QCoreApplication.translate
        ActMsgbox.setWindowTitle(_translate("ActMsgbox", "Form"))
        self.pushButton.setText(_translate("ActMsgbox", "確認"))
        self.label.setText(_translate("ActMsgbox", "當前為試用狀態\n"
"試用結束時間{ExpiryDate_formatted}：\n"
"您的序號："))
        self.textBrowser.setHtml(_translate("ActMsgbox", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft JhengHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TEST</p></body></html>"))
