# Form implementation generated from reading ui file 'c:\Users\HEXAOV\Desktop\l2_gui\GUI\Dialog_SpeechEvent.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SpeechEvent(object):
    def setupUi(self, SpeechEvent):
        SpeechEvent.setObjectName("SpeechEvent")
        SpeechEvent.resize(270, 224)
        SpeechEvent.setStyleSheet("background-color: rgb(255, 252, 235);")
        self.textBrowser = QtWidgets.QTextBrowser(parent=SpeechEvent)
        self.textBrowser.setGeometry(QtCore.QRect(10, 40, 251, 171))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("font: 700 12pt \"微軟正黑體\";\n"
"background-color: rgb(231, 255, 241);")
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(SpeechEvent)
        QtCore.QMetaObject.connectSlotsByName(SpeechEvent)

    def retranslateUi(self, SpeechEvent):
        _translate = QtCore.QCoreApplication.translate
        SpeechEvent.setWindowTitle(_translate("SpeechEvent", "演講查詢"))
        self.textBrowser.setMarkdown(_translate("SpeechEvent", "`查詢中...`\n"
"\n"
""))
        self.textBrowser.setHtml(_translate("SpeechEvent", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'微軟正黑體\'; font-size:12pt; font-weight:700; font-style:normal;\">\n"
"<p style=\" margin-top:8px; margin-bottom:8px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'標楷體\';\">查詢中...</span></p></body></html>"))
