# Form implementation generated from reading ui file 'c:\Users\HEXAOV\Desktop\l2_gui\GUI\Dialog_LaoZuo_Apply.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LaoZuo_Apply(object):
    def setupUi(self, LaoZuo_Apply):
        LaoZuo_Apply.setObjectName("LaoZuo_Apply")
        LaoZuo_Apply.resize(872, 523)
        LaoZuo_Apply.setStyleSheet("background-color: rgb(255, 252, 235);")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=LaoZuo_Apply)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 401, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_bShowOther = QtWidgets.QCheckBox(parent=self.horizontalLayoutWidget)
        self.checkBox_bShowOther.setCheckable(True)
        self.checkBox_bShowOther.setChecked(True)
        self.checkBox_bShowOther.setObjectName("checkBox_bShowOther")
        self.horizontalLayout.addWidget(self.checkBox_bShowOther)
        self.checkBox_bShowMidd = QtWidgets.QCheckBox(parent=self.horizontalLayoutWidget)
        self.checkBox_bShowMidd.setChecked(True)
        self.checkBox_bShowMidd.setObjectName("checkBox_bShowMidd")
        self.horizontalLayout.addWidget(self.checkBox_bShowMidd)
        self.checkBox_bShowPM = QtWidgets.QCheckBox(parent=self.horizontalLayoutWidget)
        self.checkBox_bShowPM.setCheckable(True)
        self.checkBox_bShowPM.setChecked(True)
        self.checkBox_bShowPM.setObjectName("checkBox_bShowPM")
        self.horizontalLayout.addWidget(self.checkBox_bShowPM)
        self.checkBox_bFilterFull = QtWidgets.QCheckBox(parent=self.horizontalLayoutWidget)
        self.checkBox_bFilterFull.setChecked(False)
        self.checkBox_bFilterFull.setObjectName("checkBox_bFilterFull")
        self.horizontalLayout.addWidget(self.checkBox_bFilterFull)
        self.tableWidget = QtWidgets.QTableWidget(parent=LaoZuo_Apply)
        self.tableWidget.setGeometry(QtCore.QRect(10, 70, 851, 411))
        self.tableWidget.setStyleSheet("font: 700 10pt \"微軟正黑體\";\n"
"background-color: rgb(231, 255, 241);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.verticalHeader().setVisible(False)
        self.btnReserve = QtWidgets.QPushButton(parent=LaoZuo_Apply)
        self.btnReserve.setGeometry(QtCore.QRect(730, 20, 121, 41))
        self.btnReserve.setObjectName("btnReserve")

        self.retranslateUi(LaoZuo_Apply)
        QtCore.QMetaObject.connectSlotsByName(LaoZuo_Apply)

    def retranslateUi(self, LaoZuo_Apply):
        _translate = QtCore.QCoreApplication.translate
        LaoZuo_Apply.setWindowTitle(_translate("LaoZuo_Apply", "目前可報名的勞作活動"))
        self.checkBox_bShowOther.setText(_translate("LaoZuo_Apply", "顯示其他時段"))
        self.checkBox_bShowMidd.setText(_translate("LaoZuo_Apply", "顯示中午時段"))
        self.checkBox_bShowPM.setText(_translate("LaoZuo_Apply", "顯示下午時段"))
        self.checkBox_bFilterFull.setText(_translate("LaoZuo_Apply", "篩掉已滿"))
        self.btnReserve.setText(_translate("LaoZuo_Apply", "[test]LaborMiner"))
