# Form implementation generated from reading ui file 'c:\Users\HEXAOV\Desktop\l2_gui\GUI\Dialog_AbsendWarning.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AbsendWarning(object):
    def setupUi(self, AbsendWarning):
        AbsendWarning.setObjectName("AbsendWarning")
        AbsendWarning.resize(538, 304)
        AbsendWarning.setStyleSheet("background-color: rgb(255, 252, 235);")
        self.textBrowser = QtWidgets.QTextBrowser(parent=AbsendWarning)
        self.textBrowser.setGeometry(QtCore.QRect(5, 41, 521, 251))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("font: 700 10pt \"微軟正黑體\";\n"
"background-color: rgb(231, 255, 241);")
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(AbsendWarning)
        QtCore.QMetaObject.connectSlotsByName(AbsendWarning)

    def retranslateUi(self, AbsendWarning):
        _translate = QtCore.QCoreApplication.translate
        AbsendWarning.setWindowTitle(_translate("AbsendWarning", "課程預警(缺曠)"))
        self.textBrowser.setMarkdown(_translate("AbsendWarning", "**課程預警|週上課時數|缺曠總節數|授課教師|科目名稱|**\n"
"\n"
""))
        self.textBrowser.setHtml(_translate("AbsendWarning", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'微軟正黑體\'; font-size:10pt; font-weight:700; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft JhengHei UI\';\">課程預警|週上課時數|缺曠總節數|授課教師|科目名稱|</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Microsoft JhengHei UI\';\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Microsoft JhengHei UI\';\"><br /></p></body></html>"))
