# Form implementation generated from reading ui file 'c:\Users\HEXAOV\Desktop\l2_gui\GUI\Dialog_ServiceQuery_Apply.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Service_Apply(object):
    def setupUi(self, Service_Apply):
        Service_Apply.setObjectName("Service_Apply")
        Service_Apply.resize(911, 523)
        Service_Apply.setStyleSheet("background-color: rgb(255, 252, 235);")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Service_Apply)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 241, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_bShowAct = QtWidgets.QCheckBox(parent=self.horizontalLayoutWidget)
        self.checkBox_bShowAct.setCheckable(True)
        self.checkBox_bShowAct.setChecked(True)
        self.checkBox_bShowAct.setObjectName("checkBox_bShowAct")
        self.horizontalLayout.addWidget(self.checkBox_bShowAct)
        self.checkBox_bShowSpeech = QtWidgets.QCheckBox(parent=self.horizontalLayoutWidget)
        self.checkBox_bShowSpeech.setChecked(True)
        self.checkBox_bShowSpeech.setObjectName("checkBox_bShowSpeech")
        self.horizontalLayout.addWidget(self.checkBox_bShowSpeech)
        self.tableWidget = QtWidgets.QTableWidget(parent=Service_Apply)
        self.tableWidget.setGeometry(QtCore.QRect(10, 70, 871, 411))
        self.tableWidget.setStyleSheet("font: 700 10pt \"微軟正黑體\";\n"
"background-color: rgb(231, 255, 241);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.verticalHeader().setVisible(False)
        self.checkBox_bFilterFull = QtWidgets.QCheckBox(parent=Service_Apply)
        self.checkBox_bFilterFull.setGeometry(QtCore.QRect(800, 30, 79, 20))
        self.checkBox_bFilterFull.setChecked(False)
        self.checkBox_bFilterFull.setObjectName("checkBox_bFilterFull")

        self.retranslateUi(Service_Apply)
        QtCore.QMetaObject.connectSlotsByName(Service_Apply)

    def retranslateUi(self, Service_Apply):
        _translate = QtCore.QCoreApplication.translate
        Service_Apply.setWindowTitle(_translate("Service_Apply", "目前可報名的服務學習活動"))
        self.checkBox_bShowAct.setText(_translate("Service_Apply", "活動"))
        self.checkBox_bShowSpeech.setText(_translate("Service_Apply", "課程演講"))
        self.checkBox_bFilterFull.setText(_translate("Service_Apply", "篩掉已滿"))
