# Form implementation generated from reading ui file 'c:\Users\HEXAOV\Desktop\l2_gui\GUI\mainView.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainViewWindow(object):
    def setupUi(self, MainViewWindow):
        MainViewWindow.setObjectName("MainViewWindow")
        MainViewWindow.resize(503, 519)
        MainViewWindow.setMouseTracking(False)
        MainViewWindow.setStyleSheet("")
        MainViewWindow.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(parent=MainViewWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"background-color: rgb(255, 252, 235);}\n"
"\n"
"\n"
"    QPushButton{\n"
"        border:0;\n"
"        font: 700 12pt ;\n"
"        border:1px solid #000;\n"
"        background:#fff;\n"
"        border-radius:10px;\n"
"    }\n"
"    QPushButton:hover{\n"
"        border:4px solid #000;\n"
"    background-color: rgb(255, 255, 0);\n"
"    }")
        self.centralwidget.setObjectName("centralwidget")
        self.label_UserID = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_UserID.setGeometry(QtCore.QRect(50, 60, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        self.label_UserID.setFont(font)
        self.label_UserID.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_UserID.setStyleSheet("        color:black;\n"
"        text-decoration: underline;\n"
"        \n"
"background-color: rgb(255, 130, 126);\n"
"        border:0;\n"
"        border:1px solid #000;\n"
"        border-radius:10px;\n"
"")
        self.label_UserID.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_UserID.setObjectName("label_UserID")
        self.btnLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnLogin.setGeometry(QtCore.QRect(390, 460, 71, 24))
        self.btnLogin.setStyleSheet("    QPushButton{\n"
"        border:0;\n"
"        font: 700 10pt ;\n"
"        border:1px solid #000;\n"
"        background-color:#fff;\n"
"        border-radius:10px;\n"
"    }\n"
"    QPushButton:hover{\n"
"        border:2px solid #000;\n"
"    \n"
"    background-color: rgb(255, 130, 126);\n"
"    }")
        self.btnLogin.setObjectName("btnLogin")
        self.label_Ver = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Ver.setGeometry(QtCore.QRect(370, 0, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_Ver.setFont(font)
        self.label_Ver.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_Ver.setStyleSheet("color: rgb(222, 222, 222);\n"
"color: rgb(167, 167, 167);")
        self.label_Ver.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_Ver.setObjectName("label_Ver")
        self.speechText = QtWidgets.QLabel(parent=self.centralwidget)
        self.speechText.setGeometry(QtCore.QRect(50, 460, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.speechText.setFont(font)
        self.speechText.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.speechText.setStyleSheet("border:0;\n"
"font: 10pt \"微軟正黑體\";\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"background-color: rgb(221, 221, 221);")
        self.speechText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.speechText.setObjectName("speechText")
        self.btnMenu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnMenu.setGeometry(QtCore.QRect(380, 20, 71, 24))
        self.btnMenu.setStyleSheet("    QPushButton{\n"
"        border:0;\n"
"        font: 700 10pt ;\n"
"        border:1px solid #000;\n"
"        background-color: rgb(255, 255, 255);\n"
"        border-radius:10px;\n"
"    }\n"
"    QPushButton:hover{\n"
"        border:2px solid #000;        \n"
"        background-color: rgb(255, 170, 0);\n"
"    }")
        self.btnMenu.setObjectName("btnMenu")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 120, 411, 321))
        self.textBrowser.setStyleSheet("")
        self.textBrowser.setObjectName("textBrowser")
        self.btnActivation = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnActivation.setGeometry(QtCore.QRect(50, 20, 91, 24))
        self.btnActivation.setStyleSheet("    QPushButton{\n"
"        border:0;\n"
"        font: 700 10pt ;\n"
"        border:1px solid #000;\n"
"        background-color: rgb(255, 255, 255);\n"
"        border-radius:10px;\n"
"    }\n"
"    QPushButton:hover{\n"
"        border:2px solid #000;        \n"
"        background-color: rgb(255, 170, 0);\n"
"    }")
        self.btnActivation.setObjectName("btnActivation")
        MainViewWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainViewWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 503, 22))
        self.menubar.setObjectName("menubar")
        MainViewWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainViewWindow)
        QtCore.QMetaObject.connectSlotsByName(MainViewWindow)

    def retranslateUi(self, MainViewWindow):
        _translate = QtCore.QCoreApplication.translate
        MainViewWindow.setWindowTitle(_translate("MainViewWindow", "GUI"))
        self.label_UserID.setText(_translate("MainViewWindow", "當前用戶：您尚未登入"))
        self.btnLogin.setText(_translate("MainViewWindow", "登入/登出"))
        self.label_Ver.setText(_translate("MainViewWindow", "0"))
        self.speechText.setText(_translate("MainViewWindow", "按下ctrl開始發言"))
        self.btnMenu.setText(_translate("MainViewWindow", "進入功能"))
        self.textBrowser.setHtml(_translate("MainViewWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft JhengHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<h1 style=\" margin-top:18px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"description\"></a><span style=\" font-size:xx-large; font-weight:700; text-decoration: underline;\">學</span><span style=\" font-size:xx-large; font-weight:700; text-decoration: underline;\">分計算機</span></h1>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">只需要輸入校往帳號密碼，就能夠協助學生計算他們目前所擁有的學分數和尚需取得的學分數的工具。<br />並且可以幫助學生輕鬆地計算他們的學分進度，並確定他們何時可以畢業。 </span></p>\n"
"<h3 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">這個計算機還包括以下功能： </span></h3>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">學分清單：學生可以輸入他們已經完成的課程和取得的學分數。這樣他們就可以清楚地知道他們還需要多少學分才能完成學位。<br /></li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">預測計算：學生可以使用這個計算機來預測他們未來的學分進度。他們可以輸入他們預計要修的課程和學分數，以及他們每學期的預計學分數。這樣他們就可以預測何時可以完成學位。<br /></li></ul>\n"
"<h3 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:medium; font-weight:700;\">此外，我們的學分計算機還具有以下特點： </span></h3>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">簡單易用：學生可以輕鬆地輸入他們的學分和課程信息，然後點擊計算按鈕便可得到他們的學分進度。<br /></li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">即時更新：當學生輸入新的課程和學分信息時，學分計算機會立即更新學分進度，讓學生始終了解他們的學位進度。<br /></li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">可定制化：學生可以選擇使用學分計算機的不同模式，以適應不同的學位計劃。<br /><br /></li></ul></body></html>"))
        self.btnActivation.setText(_translate("MainViewWindow", "btnActivation"))
